<?php

// Styles
$progress_1='disabled';
$progress_2='disabled';
$progress_3='disabled';
$progress_4='disabled';
$progress_5='disabled';
$progress_6='disabled';
if($include>=1000){
  if($include==1000){
    $progress_1='active';
  }else{
    $progress_1='finished';
    if($include>=1100){
      if($include==1100){
        $progress_2='active';
      }else{
        $progress_2='finished';
        if($include>=1200){
          if($include==1200){
            $progress_3='active';
          }else{
            $progress_3='finished';
            if($include>=1300){
              if($include==1300){
                $progress_4='active';
              }else{
                $progress_4='finished';
                if($include>=1400){
                  if($include==1400){
                    $progress_5='active';
                  }else{
                    $progress_5='finished';
                    if($include>=1500){
                      if($include==1500){
                        $progress_6='active';
                      }else{
                        $progress_6='finished';
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

ob_start();
// Load template
require_once(PCPIN_INSTALL_TEMPLATES.'/progress.tpl.php');
$_progress=ob_get_clean();
?>